import { debounce, throttle } from "../../../src/utils/common";

function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

describe("src/common/debounce.ts", () => {
  it("debounce should work", async () => {
    const fn = jest.fn();
    const debounced = debounce(fn, 25);
    debounced();
    await sleep(10);
    debounced();
    await sleep(10);
    debounced();
    await sleep(10);
    expect(fn).toHaveBeenCalledTimes(0);
    debounced();
    await sleep(10);
    expect(fn).toHaveBeenCalledTimes(0);
    debounced();
    await sleep(10);
    expect(fn).toHaveBeenCalledTimes(0);
    debounced();
    await sleep(10);
    expect(fn).toHaveBeenCalledTimes(0);
    await sleep(20);
    expect(fn).toHaveBeenCalledTimes(1);
  });
  xit("debounce should work with scope", async () => {
    const fn = jest.fn();
    const scope = { a: 1 };
    const rescope = { b: 2 };
    const debounced = debounce(fn, 25);
    debounced();
    await sleep(10);
    debounced();
    await sleep(10);
    debounced();
    await sleep(10);
    expect(fn).toHaveBeenCalledTimes(0);
    debounced();
    await sleep(10);
    expect(fn).toHaveBeenCalledTimes(0);
    debounced();
    await sleep(10);
    expect(fn).toHaveBeenCalledTimes(0);
    debounced();
    await sleep(10);
    expect(fn).toHaveBeenCalledTimes(0);
    await sleep(20);
    expect(fn).toHaveBeenCalledTimes(1);
    // debounced.setScope(rescope);
    debounced();
    expect(fn.mock.instances.length).toBe(1);
    expect(fn.mock.instances[0]).toBe(scope);
    await sleep(25);
    expect(fn.mock.instances.length).toBe(2);
    expect(fn.mock.instances[0]).toBe(scope);
    expect(fn.mock.instances[1]).toBe(rescope);
  });
  it("debounce should work with leading", async () => {
    const fn = jest.fn();
    const debounced = debounce(fn, 25, { leading: true });
    debounced();
    expect(fn).toHaveBeenCalledTimes(1);
    await sleep(10);
    debounced();
    await sleep(10);
    debounced();
    await sleep(10);
    expect(fn).toHaveBeenCalledTimes(1);
    debounced();
    await sleep(10);
    expect(fn).toHaveBeenCalledTimes(1);
    debounced();
    await sleep(10);
    expect(fn).toHaveBeenCalledTimes(1);
    debounced();
    await sleep(10);
    expect(fn).toHaveBeenCalledTimes(1);
    await sleep(20);
    expect(fn).toHaveBeenCalledTimes(2);
    debounced();
    expect(fn).toHaveBeenCalledTimes(3);
  });
});

describe("/src/common/throttle.ts", () => {
  it("throttle should work", async () => {
    const fn = jest.fn();
    const throttled = throttle(fn, 30, { leading: false });
    throttled();
    await sleep(5);
    expect(fn).toHaveBeenCalledTimes(0);
    throttled();
    expect(fn).toHaveBeenCalledTimes(0);
    throttled();
    expect(fn).toHaveBeenCalledTimes(0);
    await sleep(30);
    expect(fn).toHaveBeenCalledTimes(1);
    throttled();
    expect(fn).toHaveBeenCalledTimes(1);
    await sleep(30);
    expect(fn).toHaveBeenCalledTimes(2);
  });
  xit("throttle should work with scope", async () => {
    const fn = jest.fn();
    const scope = { a: 1 };
    const rescope = { b: 2 };
    const throttled = throttle(fn, 30);
    throttled();
    await sleep(5);
    expect(fn).toHaveBeenCalledTimes(0);
    throttled();
    expect(fn).toHaveBeenCalledTimes(0);
    throttled();
    expect(fn).toHaveBeenCalledTimes(0);
    await sleep(30);
    expect(fn).toHaveBeenCalledTimes(1);
    // throttled.setScope(rescope);
    throttled();
    expect(fn).toHaveBeenCalledTimes(1);
    await sleep(30);
    expect(fn).toHaveBeenCalledTimes(2);
    expect(fn.mock.instances.length).toBe(2);
    expect(fn.mock.instances[0]).toBe(scope);
    expect(fn.mock.instances[1]).toBe(rescope);
  });
  it("throttle should work with leading", async () => {
    const fn = jest.fn();
    const throttled = throttle(fn, 30, { leading: true, trailing: false });
    throttled();
    expect(fn).toHaveBeenCalledTimes(1);
    await sleep(5);
    expect(fn).toHaveBeenCalledTimes(1);
    throttled();
    expect(fn).toHaveBeenCalledTimes(1);
    throttled();
    expect(fn).toHaveBeenCalledTimes(1);
    await sleep(35);
    expect(fn).toHaveBeenCalledTimes(1);
    throttled();
    expect(fn).toHaveBeenCalledTimes(2);
    await sleep(35);
    expect(fn).toHaveBeenCalledTimes(2);
  });
});
